# Generated by Django 4.0.5 on 2023-03-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=250)),
                ('fani', models.TextField(blank=True)),
                ('rasmi', models.ImageField(default='default.jpg', upload_to='image')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
