# Generated by Django 4.0.5 on 2023-03-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blog_rasm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rasm',
        ),
    ]
