# Generated by Django 4.0.5 on 2023-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_managers_alter_blog_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rasm',
            field=models.ImageField(default='image/default.jpg', upload_to='image_blog'),
        ),
    ]
